services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./smart-home/ha/config/:/config
    restart: unless-stopped
    privileged: true
    network_mode: host
