name: CycloneDX Bill of Material

on:
  push:
    branches:
      - development
      - master
  workflow_dispatch:
  release:
    types: [published]

env:
  HOME_VERSION: ${{ github.ref_name }}

jobs:
  bom:
    name: Dependency BOM
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: 🐘 Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: 🌪️ Run CycloneDX
        run: ./gradlew cyclonedxBom -P version="$HOME_VERSION"

      - name: ⤴️ Upload CycloneDX bom
        uses: actions/upload-artifact@v4
        with:
          name: sbom-reports
          path: build/reports/bom.json
